In [2]:
import torch

In [3]:
mask = torch.zeros(5, dtype=torch.bool)

In [4]:
mask

tensor([False, False, False, False, False])

In [5]:
ids = torch.tensor([1, 4])

In [6]:
ids

tensor([1, 4])

In [7]:
mask.scatter_(0, ids, True)

tensor([False,  True, False, False,  True])

In [8]:
depths = torch.randn(1, 1080, 1920, 1)

In [11]:
depths.shape

torch.Size([1, 1080, 1920, 1])

In [12]:
out = depths.permute(0, 3, 1, 2)

In [13]:
out.shape

torch.Size([1, 1, 1080, 1920])